#!/bin/bash
# Phase 6 Demo: Ratatui TUI Dashboard
# Demonstrates interactive terminal UI for browsing specs

set -e

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  Manifold Phase 6 Demo: TUI Dashboard                        ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 Current specs in database:"
cargo run -q -- list 2>/dev/null

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  TUI Features Overview                                        ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Layout:"
echo "  ┌─────────────────────────────────────────────────────────────┐"
echo "  │ ╔═══════════════════════════════════════════════════════╗   │"
echo "  │ ║  Manifold Dashboard - Specification Management System ║   │"
echo "  │ ╚═══════════════════════════════════════════════════════╝   │"
echo "  ├──────────────┬────────────────────────────────────────────────┤"
echo "  │              │                                                │"
echo "  │  Specs List  │  Detail View with Tabs                        │"
echo "  │  (30%)       │  (70%)                                         │"
echo "  │              │                                                │"
echo "  │  📋 Robot... │  [Overview] [Requirements] [Tasks] [...]      │"
echo "  │  📐 Web...   │                                                │"
echo "  │              │  Workflow: ✓ requirements → [DESIGN] → ...    │"
echo "  │              │                                                │"
echo "  │              │  Requirements: 1                               │"
echo "  │              │  Tasks: 0                                      │"
echo "  │              │  Decisions: 1                                  │"
echo "  │              │                                                │"
echo "  ├──────────────┴────────────────────────────────────────────────┤"
echo "  │ ↑/↓: Navigate  Tab: Switch  1-4: Filter  r: Refresh  q: Quit │"
echo "  └─────────────────────────────────────────────────────────────┘"
echo ""
echo "Navigation:"
echo "  ↑/↓ or j/k       - Navigate through specs list"
echo "  Tab / Shift+Tab  - Switch between detail tabs"
echo "  1                - Show all specs"
echo "  2                - Filter: personal boundary"
echo "  3                - Filter: work boundary"
echo "  4                - Filter: company boundary"
echo "  r                - Refresh from database"
echo "  q / Esc / Ctrl+C - Quit"
echo ""
echo "Detail Tabs:"
echo "  1. Overview     - Workflow visualization, content summary"
echo "  2. Requirements - SHALL statements, scenarios, priorities"
echo "  3. Tasks        - Task list with requirement traceability"
echo "  4. Decisions    - Design decisions with rationale"
echo "  5. History      - Change log with timestamps"
echo ""
echo "Workflow Visualization:"
echo "  ✓ completed    → [CURRENT] → · upcoming"
echo ""
echo "Stage Icons:"
echo "  📋 requirements"
echo "  📐 design"
echo "  📝 tasks"
echo "  ✅ approval"
echo "  🎉 implemented"
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  To Launch TUI                                                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "  cargo run -- tui"
echo ""
echo "NOTE: The TUI is a fully interactive terminal application."
echo "      This demo shows the layout and features."
echo "      Run 'cargo run -- tui' to experience it!"
echo ""

# Show spec details as they would appear in TUI tabs
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  Example: Robot Control Spec - Overview Tab                  ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
cargo run -q -- show calm-flux-robot 2>/dev/null

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  Phase 6 Complete!                                            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Key features implemented:"
echo "  ✓ Full-screen terminal UI with ratatui"
echo "  ✓ Two-pane layout: spec list + detail view"
echo "  ✓ Five detail tabs: Overview, Requirements, Tasks, Decisions, History"
echo "  ✓ Visual workflow stage indicators with emojis"
echo "  ✓ Keyboard navigation (vim-style and arrows)"
echo "  ✓ Real-time filtering by boundary"
echo "  ✓ Refresh capability"
echo "  ✓ Color-coded UI elements"
echo ""
